DATA_HERE SEGMENT WORD PUBLIC
	EXTRN EFLAG: BYTE
DATA_HERE ENDS

PUBLIC DIV_PROC

PROC_HERE SEGMENT WORD PUBLIC
	DIV_PROC PROC FAR
			ASSUME CS:PROC_HERE, DS:DATA_HERE
			PUSH AX
			PUSH DS
			PUSH BX

			MOV AX, DATA_HERE
			MOV DS,AX
			
			MOV BP, SP ; INCREMENT IP BY 4
			MOV BX, WORD PTR [BP+6]
			ADD BX, 04H
			MOV [BP+6],BX
			
			MOV EFLAG,01 ; SET EFLAG(ERROR FLAG) 1
			
			POP BX
			POP DS
			POP AX
			IRET
		DIV_PROC ENDP
	PROC_HERE ENDS
END