DATA SEGMENT
	OP1 DB "ENTER A STRING :$"
	STR_BUFF DB 15,16 DUP(0)
	OP2 DB 0Dh,0Ah,"ENTER A CHARACTER :$"
	MESS1 DB 0Dh,0Ah,"CHARACTER FOUND AT THE POSITION :$"
	MESS2 DB 0Dh,0Ah,"CHARACTER NOT FOUND$"
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE , DS:DATA ,ES:DATA
START : MOV AX,DATA
		MOV DS,AX
		MOV ES,AX
		
	   MOV AH,09h
	   LEA DX,OP1                ;DISPLAY OP1 MESSAGE
	   INT 21h
		
	   MOV AH,0Ah
	   LEA DX,STR_BUFF               ;GET A STRING IN STR_BUFF
	   INT 21h
	   
	   MOV AH,09h
	   LEA DX,OP2          ;DISPLAY OP2 MESSAGE
	   INT 21h
	   
	   MOV AH,01h
	   INT 21h                     ;GET A CHARACTER
	   
	   MOV DI,OFFSET STR_BUFF+1
	   MOV CX,00
	   MOV CL,BYTE PTR[DI]
	   INC DI
	   MOV BX,DI
	   CLD
	   REPNE  SCASB
	   JNZ NOTFOUND
	   
	   MOV AH,9
	   LEA DX,MESS1               ;CHARACTER FOUND
	   INT 21h
	   
	   SUB DI,BX
	   MOV DX,DI
	   ADD DL,'0'
	   MOV AH,2
	   INT 21h
	   JMP EXIT

NOTFOUND: MOV AH,09h
		  LEA DX,MESS2          ;CHARACTER NOT FOUND
		  INT 21h

EXIT :  MOV AX,4C00h
		INT 21h
CODE ENDS

END START